name: e40_magic_8ball
description: Application used to help make difficult choice with the help of E-40&#x27;s eternal wisdom

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flame: "^0.9.5"
  flare_flutter:
  sensors: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/e40.png
    - assets/audio/nope.mp3
    - assets/audio/yep.mp3
    - assets/flare/yep.flr
    - assets/flare/nope.flr
